# Google Cloud Build configuration for KEKwallet
# Triggers on main branch merges to build the Next.js application

steps:
  # Install dependencies using pnpm
  - name: 'node:20'  # Using Node.js 20 for better compatibility and performance
    entrypoint: npm
    args: ['install', '-g', 'pnpm']

  # Install project dependencies and build
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pnpm install
        pnpm build

# Set required environment variables
options:
  env:
    - 'NEXT_PUBLIC_DEPLOYMENT_ENV=gcp'

# Timeout: 30 minutes
timeout: 1800s
