steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kekwallet'
      - '--build-arg'
      - 'NEXT_PUBLIC_DEPLOYMENT_ENV=gcp'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kekwallet']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kekwallet'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kekwallet'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_DEPLOYMENT_ENV=gcp,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY},CLERK_SECRET_KEY=${_CLERK_SECRET_KEY},NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in,NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up,NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/,NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/'

images:
  - 'gcr.io/$PROJECT_ID/kekwallet'

substitutions:
  _NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_bm90ZWQtbWFjYXF1ZS00Ny5jbGVyay5hY2NvdW50cy5kZXYk
  _CLERK_SECRET_KEY: sk_test_a20j2cuvvaRd31RRE1tP3lVuTbi59IeqalTqpu8I4N
